[build]
  # Specify which directory to publish (root directory)
  publish = "."
  
  # Ignore these directories/files during build
  ignore = "src/"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect rules (optional)
[[redirects]]
  from = "/website.html"
  to = "/"
  status = 301
